# SPDX-FileCopyrightText: Copyright Boozt Fashion, AB
# SPDX-License-Identifier: MIT
---
name: Lefthook
"on": [pull_request]
jobs:
  lefthook:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install Package
        # yamllint disable-line rule:line-length
        run: curl -1sLf 'https://dl.cloudsmith.io/public/evilmartians/lefthook/setup.deb.sh' | sudo -E bash
      - name: Install Lefthook
        run: sudo apt install lefthook && lefthook install
      - name: Run Lefthook [pre-commit] across all files
        run: lefthook run pre-commit --all-files
      - name: Run Lefthook [terraform] validation
        run: lefthook run terraform
        env:
          TF_VAR_api_token: ${{ secrets.API_TOKEN }}
          TF_VAR_account_id: ${{ secrets.ACCOUNT_ID }}
